In [3]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np
import joblib
import os
from sklearn.metrics import accuracy_score

testing_dir = "data/cross_validation/folder1/test"

# load testing data
npy_files = os.listdir(testing_dir)
testing_npy_files = [f for f in npy_files if f.endswith("features.npy")]

testing_npy_list = []
for npy_file in testing_npy_files:
    npy_path = os.path.join(testing_dir, npy_file)
    npy_array = np.load(npy_path)
    testing_npy_list.append(npy_array)

testing_features = np.concatenate(testing_npy_list, axis=0)

X_test = testing_features[:, :-1]
y_test = testing_features[:, -1]

# load rf model
rf = joblib.load("0_random_forest_0.85487.joblib")


In [4]:
# generate predictions on the test set
y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

cm = confusion_matrix(y_test, y_pred)
print(cm)

0.8548694981046204
[[2362245   49648   85473]
 [ 237613   38047   28852]
 [   3743    3099    5492]]
