In [12]:
import pandas as pd
nodulescsv = pd.read_csv("C:/Users/user/Desktop/nodule/nodules.csv")
dataset_dir = 'C:/Users/user/Desktop/nodule/final'
df_erode = pd.DataFrame(columns=["Y0", "Y1"])

print(nodulescsv.to_string)
for i in range(len(nodulescsv)-1):
    if(nodulescsv.iloc[i]['patientID'] == nodulescsv.iloc[i+1]['patientID']) and (nodulescsv.iloc[i]['num'] == nodulescsv.iloc[i+1]['num']):
        print(nodulescsv.iloc[i]['cordY'],nodulescsv.iloc[i+1]['cordY'])
        df_erode.loc[len(df_erode.index)] = [int(nodulescsv.iloc[i]['cordY']), int(nodulescsv.iloc[i+1]['cordY'])]

with pd.ExcelWriter(engine='openpyxl', path='C:/Users/user/Desktop/regression.xlsx', mode='a') as writer:
    df_erode.to_excel(writer, sheet_name='Y', index=False)

<bound method DataFrame.to_string of       patientID  filename  cordX  cordY      option  num  maintumor
0             1        60    110    229    pure GGN    1          1
1             1        61    114    226    pure GGN    1          1
2             1        62    110    227    pure GGN    1          1
3             1        63    112    228    pure GGN    1          1
4             3        26    160    207       solid    1          1
...         ...       ...    ...    ...         ...  ...        ...
2007        200        59    305    263  part solid    1          1
2008        200        60    303    264  part solid    1          1
2009        200        61    302    265  part solid    1          1
2010        200        62    302    266  part solid    1          1
2011        200        63    300    269  part solid    1          1

[2012 rows x 7 columns]>
229 226
226 227
227 228
207 210
210 208
208 208
208 208
208 209
209 206
206 210
210 216
216 213
213 213
213 213
314 312
3

In [6]:
import tensorflow as tf
import numpy as np

a = tf.constant([[[0.1,0.9],[0.2,0.8],[0.3,0.7]]])
b= tf.ones( a[:, :, 1].shape)
ones = a[:, :, 1]
print(ones)
print(b)

tf.Tensor([[0.9 0.8 0.7]], shape=(1, 3), dtype=float32)
tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)


In [3]:
import tensorflow as tf
import numpy as np

X = np.random.randint(0, 2, (100, 100, 3))
with tf.compat.v1.Session() as sess:
    X_tf = tf.compat.v1.placeholder(tf.int8)
    # X_tf.set_shape((None, None, None))
    y = tf.greater(tf.reduce_max(X_tf, axis=(0, 1)), 0)
    print(tf.shape(y))
    z = tf.boolean_mask(X_tf, y, axis=2)
    print(sess.run(z, feed_dict={X_tf: X}))

Tensor("Shape:0", shape=(None,), dtype=int32)


ValueError: Number of mask dimensions must be specified, even if some dimensions are None.  E.g. shape=[None] is ok, but shape=None is not.

In [2]:
import tensorflow as tf
a = tf.constant([2,3])
print(a)
a = a.numpy()
print(a)

tf.Tensor([2 3], shape=(2,), dtype=int32)
[2 3]


In [5]:
import os
import pandas as pd
nodulescsv = pd.read_csv("C:/Users/user/Desktop/hospital/nodules.csv")

path = 'C:/Users/user/Desktop/hospital/seg_lungimg1_120/'
for fordername in os.listdir(path):
    #print(forder)
    for filename in os.listdir(path+fordername):
        image_id = filename[:4]
        index_loc = nodulescsv.loc[(nodulescsv['patientID'] ==int(fordername)) & (nodulescsv['filename'] == int(image_id))]
        x,y = index_loc.iloc[0]['cordX'],index_loc.iloc[0]['cordY']
        print('-'*30)
        print(index_loc)
        print([x,y])
        print('-'*30)

------------------------------
   patientID  filename  cordX  cordY    option  num  maintumor
0          1        60    110    229  pure GGN    1        NaN
[110, 229]
------------------------------
------------------------------
   patientID  filename  cordX  cordY    option  num  maintumor
1          1        61    114    226  pure GGN    1        NaN
[114, 226]
------------------------------
------------------------------
   patientID  filename  cordX  cordY    option  num  maintumor
2          1        62    110    227  pure GGN    1        NaN
[110, 227]
------------------------------
------------------------------
   patientID  filename  cordX  cordY    option  num  maintumor
3          1        63    112    228  pure GGN    1        NaN
[112, 228]
------------------------------
------------------------------
    patientID  filename  cordX  cordY    option  num  maintumor
20          3        20    325    230  pure GGN    3        NaN
[325, 230]
------------------------------
---